export type World = { id: string; name: string; description: string; owner: string; members: number; events: number; branches: number; policy: "OPEN" | "REVIEW" | "INVITE ONLY" | "SOLO"; updated: string; glyph: string };
export type WikiArticleType = "Person" | "Country" | "City" | "Organization" | "Species" | "Technology" | "Culture" | "Location" | "Event" | "Custom";
export type CanonStatus = "Canon" | "Proposed" | "Non-Canon";
export type WikiRevision = { id: string; date: string; author: string; note: string };
export type WikiArticle = {
  id: string; worldId: string; type: WikiArticleType; title: string; summary: string; content: string[];
  infobox: { label: string; value: string }[]; relatedArticleIds: string[]; relatedEventIds: string[];
  creator: string; status: CanonStatus; branchId: string; branchName: string; revisions: WikiRevision[];
  backlinks: string[]; updated: string;
};

export const worlds: World[] = [
  { id: "luna-republic", name: "Luna Republic", description: "A living record of humanity's first independent civilization beyond Earth.", owner: "Mara Voss", members: 284, events: 47, branches: 8, policy: "REVIEW", updated: "12 min ago", glyph: "◒" },
  { id: "earth-17", name: "Earth—17", description: "The industrial age discovered computation two centuries early.", owner: "Ilya Chen", members: 89, events: 112, branches: 24, policy: "OPEN", updated: "1 hr ago", glyph: "◉" },
  { id: "neo-seoul", name: "Neo Seoul", description: "A city archive from the peninsula's floating century.", owner: "Joon Park", members: 51, events: 36, branches: 3, policy: "REVIEW", updated: "Yesterday", glyph: "◇" },
  { id: "verdant-signal", name: "The Verdant Signal", description: "First contact arrived as a seed, not a message.", owner: "Noa Ellis", members: 126, events: 73, branches: 17, policy: "OPEN", updated: "2 hr ago", glyph: "✦" },
];

export const timeline = [
  { id: "e1", year: "2026", title: "Lunar settlement founded", text: "Thirty-two settlers establish the first permanent habitation at Shackleton Crater.", x: 110, y: 90, important: false, articleIds: ["artemis"] },
  { id: "e2", year: "2030", title: "Population reaches 10,000", text: "The settlements become a permanent civic society with their own institutions.", x: 310, y: 90, important: false, articleIds: ["artemis", "lunar-assembly"] },
  { id: "e3", year: "2034", title: "Moon declares independence", text: "Representatives of the lunar colonies sign the Lunar Declaration.", x: 510, y: 90, important: true, articleIds: ["lunar-republic", "mara-voss", "lunar-assembly"] },
  { id: "e4", year: "2035", title: "Earth imposes sanctions", text: "Earth governments suspend trade and restrict orbital access.", x: 710, y: 90, important: false, articleIds: ["lunar-republic"] },
  { id: "e5", year: "2034", title: "Federation Agreement", text: "An alternate settlement binds Earth and Moon under a shared charter.", x: 710, y: 250, important: true, articleIds: ["federation-charter", "lunar-republic-federation"] },
];

export const articleTypes: WikiArticleType[] = ["Person", "Country", "City", "Organization", "Species", "Technology", "Culture", "Location", "Event", "Custom"];
export const branches = [{ id: "main", name: "Main worldline" }, { id: "federation", name: "Federation line" }, { id: "silent-orbit", name: "Silent Orbit" }];

export const wikiArticles: WikiArticle[] = [
  { id:"lunar-republic", worldId:"luna-republic", type:"Country", title:"Lunar Republic", summary:"The first sovereign human nation founded beyond Earth.", content:["The Lunar Republic is a federal parliamentary state spanning the permanent settlements of the lunar south pole. It emerged from the colonial assemblies that coordinated life-support, transport, and resource rights during the first decade of settlement.","Its declaration of independence in 2034 transformed a network of municipal habitats into a single political body. Recognition remains disputed by several Earth governments, making the Republic the central question of the Main Worldline."], infobox:[{label:"Founded",value:"14 July 2034"},{label:"Capital",value:"Artemis"},{label:"Population",value:"12.4 million"},{label:"Government",value:"Federal republic"},{label:"Demonym",value:"Lunar"}], relatedArticleIds:["artemis","lunar-assembly","mara-voss"], relatedEventIds:["e3","e4"], creator:"Mara Voss", status:"Canon", branchId:"main", branchName:"Main worldline", revisions:[{id:"r18",date:"18 Sep 2036",author:"Mara Voss",note:"Clarified recognition dispute"},{id:"r17",date:"12 Sep 2036",author:"Soren Yi",note:"Updated population census"},{id:"r1",date:"14 Jul 2034",author:"Mara Voss",note:"Created article"}], backlinks:["artemis","lunar-assembly","mara-voss"], updated:"12 min ago" },
  { id:"lunar-republic-federation", worldId:"luna-republic", type:"Country", title:"Lunar Republic", summary:"A self-governing lunar territory within the Earth–Moon Federation.", content:["In the Federation worldline, the declaration crisis concluded with a shared charter rather than independence. The Lunar Republic exists as an autonomous territory with representation in a bicameral federal assembly.","This record diverges from the Main Worldline at the ratification vote of 2034. Names shared between branches refer to the same inherited entity, but facts after the fork are versioned independently."], infobox:[{label:"Reconstituted",value:"2 November 2034"},{label:"Capital",value:"Artemis"},{label:"Status",value:"Federal territory"},{label:"Parent polity",value:"Earth–Moon Federation"}], relatedArticleIds:["artemis","federation-charter"], relatedEventIds:["e5"], creator:"Elena R.", status:"Proposed", branchId:"federation", branchName:"Federation line", revisions:[{id:"rf3",date:"20 Sep 2036",author:"Elena R.",note:"Aligned with charter draft"},{id:"rf1",date:"2 Nov 2034",author:"Elena R.",note:"Forked from Main version"}], backlinks:["federation-charter"], updated:"34 min ago" },
  { id:"artemis", worldId:"luna-republic", type:"City", title:"Artemis", summary:"Capital city of the Lunar Republic, built along Shackleton Crater.", content:["Artemis began as a pressurized settlement built into the permanently shadowed rim of Shackleton Crater. Its layered galleries house the Assembly, the civil archive, and the southern transit interchange.","The city is linked throughout this archive to the settlement's founding, the first census, and the constitutional period."], infobox:[{label:"Established",value:"2026"},{label:"Population",value:"4.8 million"},{label:"Region",value:"Lunar south pole"},{label:"Elevation",value:"−1.2 km"}], relatedArticleIds:["lunar-republic","lunar-assembly"], relatedEventIds:["e1","e2"], creator:"Noa Ellis", status:"Canon", branchId:"main", branchName:"Main worldline", revisions:[{id:"a8",date:"17 Sep 2036",author:"Noa Ellis",note:"Added transit interchange"},{id:"a1",date:"8 Jan 2026",author:"Noa Ellis",note:"Created article"}], backlinks:["lunar-republic","lunar-assembly"], updated:"2 hr ago" },
  { id:"mara-voss", worldId:"luna-republic", type:"Person", title:"Mara Voss", summary:"Constitutional archivist and first curator of the Lunar Record.", content:["Mara Voss organized the distributed record used by the settlements during the independence convention. Her annotations became the basis of the public Lunar Archive."], infobox:[{label:"Born",value:"2001 · Bremen"},{label:"Occupation",value:"Archivist"},{label:"Affiliation",value:"Lunar Assembly"}], relatedArticleIds:["lunar-republic","lunar-assembly"], relatedEventIds:["e3"], creator:"Ilya Chen", status:"Canon", branchId:"main", branchName:"Main worldline", revisions:[{id:"m4",date:"10 Sep 2036",author:"Ilya Chen",note:"Added convention record"}], backlinks:["lunar-republic"], updated:"1 day ago" },
  { id:"lunar-assembly", worldId:"luna-republic", type:"Organization", title:"Lunar Assembly", summary:"The elected deliberative body governing the lunar settlements.", content:["The Assembly grew out of the habitat council, where settlements negotiated shared oxygen reserves and transit windows. It became the Republic's legislature after independence."], infobox:[{label:"Formed",value:"2029"},{label:"Seats",value:"144"},{label:"Meeting place",value:"Artemis Forum"}], relatedArticleIds:["lunar-republic","artemis","mara-voss"], relatedEventIds:["e2","e3"], creator:"Soren Yi", status:"Canon", branchId:"main", branchName:"Main worldline", revisions:[{id:"la7",date:"14 Sep 2036",author:"Soren Yi",note:"Revised seat count"}], backlinks:["lunar-republic","artemis","mara-voss"], updated:"3 days ago" },
  { id:"federation-charter", worldId:"luna-republic", type:"Event", title:"Federation Charter", summary:"The proposed compact resolving the 2034 sovereignty crisis.", content:["The charter is only valid in the Federation line. It divides authority over orbital defense, trade, and citizenship between Earth and lunar governments."], infobox:[{label:"Signed",value:"2 November 2034"},{label:"Status",value:"Awaiting ratification"},{label:"Worldline",value:"Federation line"}], relatedArticleIds:["lunar-republic-federation"], relatedEventIds:["e5"], creator:"Elena R.", status:"Proposed", branchId:"federation", branchName:"Federation line", revisions:[{id:"fc2",date:"19 Sep 2036",author:"Elena R.",note:"Added citizenship article"}], backlinks:["lunar-republic-federation"], updated:"4 hr ago" },
  { id:"helium-cooperatives", worldId:"luna-republic", type:"Organization", title:"Helium Cooperatives", summary:"A contested account of informal mining syndicates in the far-side territories.", content:["This article collects disputed testimony and has not been accepted into either active worldline."], infobox:[{label:"Alleged formation",value:"2031"},{label:"Evidence",value:"Disputed"}], relatedArticleIds:["lunar-republic"], relatedEventIds:[], creator:"T. Okafor", status:"Non-Canon", branchId:"main", branchName:"Main worldline", revisions:[{id:"hc1",date:"8 Sep 2036",author:"T. Okafor",note:"Submitted research note"}], backlinks:[], updated:"1 week ago" }
];

export function worldById(id:string) { return worlds.find(world=>world.id===id); }
export function articleById(id:string) { return wikiArticles.find(article=>article.id===id); }
export function articleVersions(title:string) { return wikiArticles.filter(article=>article.title===title); }
